version: "3.9"
services:
  overworld:
    image: yeetzone/dontstarvetogether:next
    container_name: overworld
    hostname: overworld
    environment:
      TOKEN: TOKEN
    ports:
      - "10999:10999/udp"
    volumes:
      - type: volume
        source: data
        target: /data
        read_only: true
        volume:
          nocopy: true
  data:
    image: yeetzone/dontstarvetogether-data:next
    volumes:
      - type: volume
        source: data
        target: /data
        read_only: true
volumes:
  data:
